services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sportlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d sportlink"]
      interval: 5s
      timeout: 3s
      retries: 10

  maildev:
    image: maildev/maildev:2
    ports: ["1080:1080", "1025:1025"]

  app:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sportlink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
      SECURITY_JWT_SECRET: change-me-very-long-random-secret-32b-min
      SECURITY_JWT_EXPIRATIONMS: 86400000
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
